### ISSUE TITLE
Add Xiling project file to the repo

### ISSUE THREAD

**Issue by secworks** [bunnie/novena-gpbb-fpga#1]
It would be much easier to build the design if you could include an ISE project file (.xise) that imports all relevant RTL files, the UCF and the correct FPGA type. The PlanAhead file does not do this.

**Comment by bunnie** [comment]
thanks -- I only use the PlanAhead design flow, I stopped using the ISE
UI a while ago. But, maybe you can upload your .xise file if that's what
you use.

-b.

On 11/11/2014 04:40 AM, Joachim Strömbergson wrote:

> It would be much easier to build the design if you could include an ISE
> project file (.xise) that imports all relevant RTL files, the UCF and
> the correct FPGA type. The PlanAhead file does not do this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bunnie/novena-gpbb-fpga/issues/1.

## 

^`'~*-,._.^`'~_-,._.^`'~_-,._.^`'~*-,._.^`'~*-,._.^`'~_-,._.^`'~_-,._.^`'

**Comment by secworks** [comment]
mega old. closing this.
